### PR TITLE
setup deploy on push to master with tags

### PR DESCRIPTION
**Pull request by hzoo**
didn't know about https://github.com/DrewML/chrome-webstore-upload-cli (found it looking at refined github again)

@DrewML

### CODE REVIEW

**Comment by hzoo** [comment]
Hmm getting

`Response code 403 (Forbidden)` from https://travis-ci.org/hzoo/contributors-on-github/builds/159326866

I added CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN

**Comment by DrewML** [comment]
@hzoo I setup a reminder for myself to take a look for you after work tonight.

**Comment by DrewML** [comment]
💩  Really starting to wish I added more diagnostics for failures. Would probably be good in the future for me to log progress so it's clear whether it fails during token refresh, upload, or publish.

Can you try running the command locally (after setting the env vars in your shell) and tell me what step it looks like it is failing on? The spinner component being used clears it's previously value in the shell when it moves on to the next step of the process, so you can't see those steps when running in CI.

**Comment by DrewML** [comment]
It might also be worth going through [step 9](https://developer.chrome.com/webstore/using_webstore_api) again and getting a new refresh token. Going through that step will also help verify the `CLIENT_ID` and `CLIENT_SECRET` are still valid.

**Comment by hzoo** [comment]
I tried to run it locally and I'm getting the same error and no other info?

> github-contributor-extension@1.0.0 release /Users/hzhu/dev/github-contributor-extension
> webstore upload --source=src --auto-publish

> Response code 403 (Forbidden)

> npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/hzhu/.nvm/versions/node/v6.3.0/bin/node" "/Users/hzhu/.nvm/versions/node/v6.3.0/bin/npm" "run" "release"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! github-contributor-extension@1.0.0 release: `webstore upload --source=src --auto-publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the github-contributor-extension@1.0.0 release script 'webstore upload --source=src --auto-publish'.

**Comment by hzoo** [comment]
Looks like it's failing on https://github.com/DrewML/chrome-webstore-upload/blob/master/index.js#L37 if I check manually

**Comment by hzoo** [comment]
Ok... seriously - it seems like the `Chrome Web Store API has not been used in project before or it is disabled` - it wasn't enabled??

IT WORKS

**Comment by DrewML** [comment]
> IT WORKS

YAY!

**Pull request merged**
