### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by djrosenbaum**
Ref: #14 

Designed logo idea with Git branching and nodes.

Ignore .DS_Store

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
IMO, 512d000 looks not so related to this PR.

**Comment by hzoo** [comment]
it's a good addition (although unrelated)

**Comment by PeterDaveHello** [comment]
Since it's not a project related config, why not put that ignore in users' global gitignore config?

**Comment by Pocket-titan** [comment]
@hzoo Sure thing, I don't mind :)

@PeterDaveHello I agree, adding .DS_Store to .gitignore is completely unrelated to this repo & it's better practice to put it in a global config

**Comment by hzoo** [comment]
good points!

**Comment by hzoo** [comment]
Also looks like you need all 3 sizes

**Pull request merged**
